version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  springboot-app:
    image: journal:v3
    container_name: journal-collabplatform
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATA_MONGODB_PORT=27017

volumes:
  mongo_data:
